name: MagicSpells
main: com.nisovin.magicspells.MagicSpells
version: 2.7-test
author: nisovin
softdepend: [BookWorm,WorldGuard,Residence]
commands:
    magicspellcast:
        description: Cast a spell
        usage: /<command>
        aliases: [cast,c]
    magicspellmana:
        description: Show mana bar
        usage: /<command>
        aliases: [mana]
permissions:
    magicspells.silent:
        description: Cast spells without spell text messages
        default: false